name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      # - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          echo "Just variable ${{MALI}}"
          echo "${{REPO_TOKEN}}"
          echo "$STEP_VAR"
          # Your ML workflow goes here
          # pip install -r requirements.txt
          # python train.py
          
          # echo "## Data Viz " > report.md
          # cat metrics.txt >> report.md
          
          # cml-publish feature_importance.pgn --md >> report.md
          # cml-publish residuals.png --md >> report.md
          
          # cml-send-comment report.md
        env:
          STEP_VAR: local variable
