name: Retrain and validate model on data change

on:
  push:
    paths:
      - 'data/wine_quality.csv'

jobs:
  train_and_validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create virtual environment
      run: |
        python -m venv venv
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          echo "venv\\Scripts\\activate" > activate.sh
        else
          echo "source venv/bin/activate" > activate.sh
        fi
        chmod +x activate.sh

    - name: Install dependencies
      run: |
        . ./activate.sh
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install python3-distutils -y
        fi
        python -m pip install --upgrade setuptools pip
        pip install -r requirements.txt

    - name: Train model
      run: |
        . ./activate.sh
        python scripts/train_model.py

    - name: Validate model
      id: validate
      run: |
        . ./activate.sh
        python scripts/validate_model.py
    
    - name: Hyperparameter tuning
      if: steps.validate.outcome == 'failure'
      run: |
        . ./activate.sh
        python scripts/hyperparameter_tuning.py