name: model_wine_quality
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: checkout
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Set up Python 3.x
      
      - name: Train model
        run: |
          pip install -r requirements.txt
          python train.py
        
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model metrics" > report.md
          cat results.txt >> report.md
