name: Testing when pushing or PR to master
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Train model
        run: |
          python scripts/train_model.py
          
      - name: Validate model
        id: validate
        run: |
          python scripts/validate_model.py
      
      # - name: Train the model if validation fails
      #   if: steps.validate.outcome == 'failure'
      #   run: |
      #     python scripts/train_model.py