name: Testing when pushing or PR to master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  train_and_validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Create virtual environment
        run: |
            python -m venv venv
            $venvPath = if ($env:RUNNER_OS -eq 'Windows') { '.\venv\Scripts\activate' } else { 'source venv/bin/activate' }
            echo $venvPath > activate_path

      - name: Install dependencies
        run: |
          . ./activate.sh
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install python3-distutils -y
          fi
          python -m pip install --upgrade setuptools pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          . ./activate.sh
          python scripts/train_model.py

      - name: Validate model
        id: validate
        run: |
          . ./activate.sh
          python scripts/validate_model.py

      # - name: Train the model if validation fails
      #   if: steps.validate.outcome == 'failure'
      #   run: |
      #     . ./activate.sh
      #     python scripts/train_model.py